### ISSUE TITLE
flexfloat_get_bits() gives wrong results

### ISSUE THREAD

**Issue by cappellini** [oprecomp/flexfloat#14]
flexfloat_get_bits() gives wrong results when the bit representation is a power of 2 and the flexfloat is denormalized (exp <= 0).

For example 
```cpp
flexfloat_t test;

ff_init(&test, {5, 10});
flexfloat_set_bits(&test, 8);
std::cout << flexfloat_get_bits(&test) << std::endl;
```
gives the output `18446744073709545472`.

This is most likely due to the line `else if(exp <= 0 && frac != 0)` in

```cpp
uint_t flexfloat_get_bits(flexfloat_t *a)
{
    int_fast16_t exp = flexfloat_exp(a);
    uint_t frac = flexfloat_frac(a);

    if(exp == INF_EXP) exp = flexfloat_inf_exp(a->desc);
    else if(exp <= 0 && frac != 0) {
        frac = flexfloat_denorm_frac(a, exp);
        exp = 0;
    }

    return ((uint_t)flexfloat_sign(a) << (a->desc.exp_bits + a->desc.frac_bits))
           + ((uint_t)exp << a->desc.frac_bits)
           + frac;
}
```

What is the `&& frac != 0`  for? Without it, it seems to work (at least for my example).

**Comment by gtagliavini** [comment]
I confirm that the aforementioned check (frac != 0) is wrong in this context. After executing all the tests to avoid regressions, I'll commit a patch fixing this issue. Thank you very much for your collaboration!
